{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
apiVersion: v1
data:
  RDSHOST: {{ $depServices.rds.host | quote }}
  RDSPORT: {{ quote $depServices.rds.port }}
  RDSUSER: {{ $depServices.rds.user }}
  RDSPASS: {{ $depServices.rds.password }}
  DB_TYPE: {{ $depServices.rds.type | quote}}
  RDSDBNAME: {{ $depServices.rds.database | quote }}
  OPENSEARCH_HOST: {{ $depServices.opensearch.host | quote}}
  OPENSEARCHRED: {{ $depServices.opensearch.read | quote}}
  OPENSEARCHWRITE: {{ $depServices.opensearch.write | quote}}
  OPENSEARCH_PORT: {{ quote $depServices.opensearch.port }}
  OPENSEARCH_USER: {{ $depServices.opensearch.user | quote}}
  OPENSEARCH_PASS: {{ $depServices.opensearch.password | quote}}
  REDISCLUSTERMODE: {{ $depServices.redis.connectType | quote}}
  REDISUSER: {{ $depServices.redis.connectInfo.username | quote}}
  REDISPASS: {{ $depServices.redis.connectInfo.password | quote}}
  {{- if eq $depServices.redis.connectType "sentinel" }}
  REDISHOST: {{ quote $depServices.redis.connectInfo.sentinelHost }}
  REDISPORT: {{ quote $depServices.redis.connectInfo.sentinelPort }}
  SENTINELMASTER: {{ $depServices.redis.connectInfo.masterGroupName | quote }}
  SENTINELUSER: {{ $depServices.redis.connectInfo.sentinelUsername | quote}}
  SENTINELPASS: {{ $depServices.redis.connectInfo.sentinelPassword | quote}}
  {{- else if eq $depServices.redis.connectType "standalone" }}
  REDISHOST: {{ quote $depServices.redis.connectInfo.host }}
  REDISPORT: {{ quote $depServices.redis.connectInfo.port }}
  {{- else if eq $depServices.redis.connectType "master-slave" }}
  REDISREADHOST: {{ $depServices.redis.connectInfo.slaveHost | quote}}
  REDISREADPORT: {{ quote $depServices.redis.connectInfo.slavePort }}
  REDISREADUSER: {{ $depServices.redis.connectInfo.username | quote}}
  REDISREADPASS: {{ $depServices.redis.connectInfo.password | quote}}
  REDISWRITEHOST: {{ $depServices.redis.connectInfo.masterHost | quote}}
  REDISWRITEPORT: {{ quote $depServices.redis.connectInfo.masterPort }}
  REDISWRITEUSER: {{ $depServices.redis.connectInfo.username | quote}}
  REDISWRITEPASS: {{ $depServices.redis.connectInfo.password | quote}}
  {{- end }}
  KAFKAHOST: {{ $depServices.mq.mqHost | quote }}
  KAFKAPORT: {{ quote $depServices.mq.mqPort }}
  KAFKAUSER: {{ $depServices.mq.auth.username | quote }}
  KAFKAPASS: {{ $depServices.mq.auth.password | quote }}
  TEXTVECTORMAPPING: {{ quote $depServices.text_vector.mapping | quote }}
  VLMVECTORMAPPING: {{ quote $depServices.text_vector.mapping | quote }}
  TEXTRERANKERMAPPING: {{ quote $depServices.text_reranker.mapping | quote }}
  # 授权服务
  OAUTHPUBLICHOST: {{ $depServices.hydra.publicHost | quote }}
  OAUTHPUBLICPORT: {{ $depServices.hydra.publicPort | quote }}
  OAUTHADMINHOST: {{ $depServices.hydra.administrativeHost | quote }}
  OAUTHADMINPORT: {{ $depServices.hydra.administrativePort | quote }}
  # user-management服务
  USERMANAGEMENTPUBLICHOST: {{ $depServices.user_management.publicHost | quote }}
  USERMANAGEMENTPUBLICPORT: {{ $depServices.user_management.publicPort | quote }}
  USERMANAGEMENTPRIVATEHOST: {{ $depServices.user_management.privateHost | quote }}
  USERMANAGEMENTPRIVATEPORT: {{ $depServices.user_management.privatePort | quote }}
  # authorization服务
  AUTHORIZATIONPRIVATEHOST: {{ $depServices.authorization.privateHost | quote }}
  AUTHORIZATIONPRIVATEPORT: {{ $depServices.authorization.privatePort | quote }}
  dm_svc.conf: |
    TIME_ZON=(480)
    LANGUAGE=(cn)
    DM={{ printf "(%s)" .Values.depServices.rds.host }}
    [DM]
    LOGIN_MODE=(1)

kind: ConfigMap
metadata:
  name: {{ .Values.image.name }}-yaml
  namespace: {{ .Release.Namespace }}
