---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
  name: {{ include "template.fullname" $ }}-static
  labels:
    {{- include "template.labels" $ | nindent 4 }}
spec:
  type: "ClusterIP"
  {{- if $.Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  ports:
  - port: 18800
    targetPort: 18800
    protocol: TCP
    name: staticport
  selector:
    {{- include "template.selectorLabels" $ | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
  name: {{ include "template.fullname" $ }}-service
  labels:
    {{- include "template.labels" $ | nindent 4 }}
spec:
  type: "ClusterIP"
  {{- if $.Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  ports:
  - port: 18080
    targetPort: 18080
    protocol: TCP
    name: serviceport
  - port: 18880
    targetPort: 18880
    protocol: TCP
    name: app
  selector:
    {{- include "template.selectorLabels" $ | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
  name: {{ $.Values.image.business_system.name }}
  labels:
    {{- include "template.labels" $ | nindent 4 }}
spec:
  type: "ClusterIP"
  {{- if $.Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  ports:
  - port: 88
    targetPort: 88
    protocol: TCP
    name: businesshttp
  - port: 440
    targetPort: 440
    protocol: TCP
    name: businesshttps
  selector:
    {{- include "template.selectorLabels" $ | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
  name: {{ $.Values.image.model_manager.name }}
  labels:
    {{- include "template.labels" $ | nindent 4 }}
spec:
  type: "ClusterIP"
  {{- if $.Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    {{- include "template.selectorLabels" $ | nindent 4 }}
