{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
{{- $configMapName := printf "%s-yaml" .Values.image.name -}}
{{- $rdsConfVolume := printf "%s-rds-conf" .Values.image.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ include "mergedGlobalValues.replicaCount" . }}
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | trunc 10 | quote }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          image: "{{ include "mergedGlobalValues.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: model-factory
              containerPort: {{ .Values.service.ports.port }}
          livenessProbe:
            httpGet:
              path: /api/v1/health/alive
              port: {{ .Values.service.ports.port }}
            initialDelaySeconds: 30
            periodSeconds: 300
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/v1/health/ready
              port: {{ .Values.service.ports.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: {{ $rdsConfVolume }}
              mountPath: /tmp/rds_conf
          env:
            - name: DEVICE_CODE
              value: {{ .Values.env.devicecode }}
            - name: RDSHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: RDSHOST
            - name: RDSPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: RDSPORT
            - name: RDSUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: RDSUSER
            - name: RDSPASS
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: RDSPASS
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: DB_TYPE
            - name: RDSDBNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: RDSDBNAME
            - name: OPENSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: OPENSEARCH_HOST
            - name: OPENSEARCHWRITE
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: OPENSEARCHWRITE
            - name: OPENSEARCHREAD
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: OPENSEARCHRED
            - name: OPENSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: OPENSEARCH_PORT
            - name: OPENSEARCH_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: OPENSEARCH_USER
            - name: OPENSEARCH_PASS
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: OPENSEARCH_PASS
            - name: REDISCLUSTERMODE
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISCLUSTERMODE
            - name: REDISUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISUSER
            - name: REDISPASS
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISPASS
            {{- if ne $depServices.redis.connectType "master-slave" }}
            - name: REDISHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISHOST
            - name: REDISPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISPORT
            {{- end }}
            {{- if eq $depServices.redis.connectType "sentinel" }}
            - name: SENTINELMASTER
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: SENTINELMASTER
            - name: SENTINELUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: SENTINELUSER
            - name: SENTINELPASS
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: SENTINELPASS
            {{- end }}
            {{- if eq $depServices.redis.connectType "master-slave" }}
            - name: REDISREADHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISREADHOST
            - name: REDISREADPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISREADPORT
            - name: REDISREADUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISREADUSER
            - name: REDISREADPASS
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISREADPASS
            - name: REDISWRITEHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISWRITEHOST
            - name: REDISWRITEPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISWRITEPORT
            - name: REDISWRITEUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISWRITEUSER
            - name: REDISWRITEPASS
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: REDISWRITEPASS
            {{- end }}
            - name: KAFKAHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: KAFKAHOST
            - name: KAFKAPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: KAFKAPORT
            - name: KAFKAUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: KAFKAUSER
            - name: KAFKAPASS
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: KAFKAPASS
            # 修复以下三个环境变量的配置
            - name: TEXTVECTORMAPPING
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: TEXTVECTORMAPPING
            - name: VLMVECTORMAPPING
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: VLMVECTORMAPPING
            - name: TEXTRERANKERMAPPING
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: TEXTRERANKERMAPPING
            - name: DM_SVC_PATH
              value: /tmp/rds_conf/
            - name: OAUTHPUBLICHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: OAUTHPUBLICHOST
            - name: OAUTHPUBLICPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: OAUTHPUBLICPORT
            - name: OAUTHADMINHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: OAUTHADMINHOST
            - name: OAUTHADMINPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: OAUTHADMINPORT
            - name: USERMANAGEMENTPUBLICHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: USERMANAGEMENTPUBLICHOST
            - name: USERMANAGEMENTPUBLICPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: USERMANAGEMENTPUBLICPORT
            - name: USERMANAGEMENTPRIVATEHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: USERMANAGEMENTPRIVATEHOST
            - name: USERMANAGEMENTPRIVATEPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: USERMANAGEMENTPRIVATEPORT
            - name: AUTHORIZATIONPRIVATEHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: AUTHORIZATIONPRIVATEHOST
            - name: AUTHORIZATIONPRIVATEPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: AUTHORIZATIONPRIVATEPORT
            # 可观测相关配置
            - name: LOG_ENABLED
              value: {{ .Values.observability.logEnabled | quote }}
            - name: TRACE_ENABLED
              value: {{ .Values.observability.traceEnabled | quote }}
            - name: METRIC_ENABLED
              value: {{ .Values.observability.metricEnabled | quote }}
            - name: LOG_EXPORTER
              value: {{ .Values.observability.logExporter }}
            - name: TRACE_PROVIDER
              value: {{ .Values.observability.traceProvider }}
            - name: METRIC_PROVIDER
              value: {{ .Values.observability.metricProvider }}
            - name: LOG_LOAD_INTERNAL
              value: {{ .Values.observability.logLoadInternal | quote }}
            - name: LOG_LOAD_MAX_LOG
              value: {{ .Values.observability.logLoadMaxLog | quote }}
            - name: TRACE_MAX_QUEUE_SIZE
              value: {{ .Values.observability.traceMaxQueueSize | quote }}
            - name: METRIC_INTERVAL_SECOND
              value: {{ .Values.observability.metricIntervalSecond | quote }}
            - name: HTTP_LOG_FEED_INGESTER_URL
              value: {{ .Values.observability.httpLogFeedIngesterUrl }}
            - name: HTTP_TRACE_FEED_INGESTER_URL
              value: {{ .Values.observability.httpTraceFeedIngesterUrl }}
            - name: HTTP_METRIC_FEED_INGESTER_URL
              value: {{ .Values.observability.httpMetricFeedIngesterUrl }}
            - name: GRPC_TRACE_FEED_INGESTER_URL
              value: {{ .Values.observability.grpcTraceFeedIngesterUrl }}
            - name: GRPC_TRACE_JOB_ID
              value: {{ .Values.observability.grpcTraceJobId }}
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: {{ $rdsConfVolume }}
          configMap:
            name: {{ $configMapName }}
            items:
            - key: dm_svc.conf
              path: dm_svc.conf
