{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
{{- $accessAddress := include "mergedGlobalValues.accessAddress" . | fromYaml -}}
apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "template.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
data: 
  depServices.yaml: |
    {{- toYaml $depServices |  nindent 4 }}
  accessAddr.yaml: |
    {{- toYaml $accessAddress |  nindent 4 }}

